name 'mysecondcookbook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures mysecondcookbook'
long_description 'Installs/Configures mysecondcookbook'
version '0.1.0'
