name 'mythiredcookbook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures mythiredcookbook'
long_description 'Installs/Configures mythiredcookbook'
version '0.1.0'
