name 'Ta7leel'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures Ta7leel'
long_description 'Installs/Configures Ta7leel'
version '0.1.0'

depends 'selinux', '~> 0.9.0'
depends 'firewall', '~> 2.4.0'
depends 'httpd', '~> 0.4.0'
depends 'mysql', '~> 7.0.0'
depends 'mysql2_chef_gem', '~> 1.1.0'
depends 'database', '~> 5.1.2'
depends 'phpmyadmin', '~> 1.0.8'
depends 'vsftpd', '~> 0.1.0'
depends 'tomcat', '~> 2.3.1'
depends 'java', '~> 1.42.0'