name 'ip3'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ip3'
long_description 'Installs/Configures ip3'
version '0.1.0'

depends 'selinux', '~> 0.9.0'
depends 'firewall', '~> 2.4.0'
depends 'httpd', '~> 0.4.0'
depends 'mysql', '~> 7.0.0'
depends 'mysql2_chef_gem', '~> 1.1.0'
depends 'database', '~> 5.1.2'
depends 'tomcat', '~> 2.3.1'
depends 'java_se', '~> 8.92.0'
depends 'phpmyadmin', '~> 1.0.8'
depends 'vsftpd', '~> 0.1.0'